### ISSUE TITLE
Duplicate Code

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/DSC#10]
Some of the states duplicate a lot of code:
![image](https://user-images.githubusercontent.com/26659428/86846365-c875e700-c078-11ea-9dd9-f5b8e0b200be.png)
Try to put these functions into their own states and call them using Macros

**Comment by motasemelgamel** [comment]
I created a new state "Data: Get Time Interval" that will take care of these time interval codes. I will push changes now.

**Comment by ciozi137** [comment]
Sounds good, thanks. I will look at it tomorrow.

**Comment by ciozi137** [comment]
There is an a lot of duplicate code here:

![image](https://user-images.githubusercontent.com/26659428/87058721-64693500-c1d6-11ea-9db4-a65aca1e4a4a.png)

==

![image](https://user-images.githubusercontent.com/26659428/87058795-82cf3080-c1d6-11ea-95de-5ad91268d054.png)

**Comment by ciozi137** [comment]
new code looks like this:
![image](https://user-images.githubusercontent.com/26659428/87060933-1ace1980-c1d9-11ea-97ba-4a662b0ce493.png)
