### ISSUE TITLE
(Un)Bundle vs (Un)Bundle by Name

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/DSC#12]
@mo3tasem98 there is something strange happening. I had replaced all of these with the "by name" version:
![image](https://user-images.githubusercontent.com/26659428/87051918-308a1180-c1ce-11ea-921e-9a0670dbd45d.png)

But when I open the code you just pushed it looks like this:
![image](https://user-images.githubusercontent.com/26659428/87051718-f28ced80-c1cd-11ea-8610-f13b0fcb1b3b.png)

**Comment by motasemelgamel** [comment]
I was updating the code I wrote originally. I didn't know you pushed these changes.

**Comment by ciozi137** [comment]
ok I will change them and push my code this morning.
Here is something else to watch for:
![image](https://user-images.githubusercontent.com/26659428/87053388-e570fe00-c1cf-11ea-8057-2ec4677b1b72.png)
