### ISSUE TITLE
Front panel configuration

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/DSC#18]
1. Store previous "good" configuration in configuration file. Use the configuration methods from the Instruments package

See here for discussion and example code in the AFM Lithography project: https://github.com/levylabpitt/AFM-Lithography/issues/5

2. Store select-able user presets in a configuration file(s)

**Comment by motasemelgamel** [comment]
I added new states called "configuration" that save/load configurations. I did it such that the configuration file will contain all front panel objects values, I wasn't sure if that's how it is supposed to be. The user will also be able to save/load whenever he wants through save/load options I added to the front panel. I pushed the changes to dev-pg branch
