### ISSUE TITLE
What happens if database isn't found?

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/DSC#19]
The application should fail gracefully
- alert the user?
- ask for another database path?
- ??

**Comment by motasemelgamel** [comment]
A message box will be shown telling the user that DSC database can't be found

**Comment by ciozi137** [comment]
What happens after that?

**Comment by motasemelgamel** [comment]
Nothing really. It just alerts the user and the user should check his connection to the database. Do you suggest adding anything?
