### ISSUE TITLE
Database Viewer: Show/Hide GUI elements

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/DSC#20]
## Show tree control:
![image](https://user-images.githubusercontent.com/26659428/87183334-f2ffb400-c2b3-11ea-9dd0-f3c532deeae9.png)

## Hide tree control:
![image](https://user-images.githubusercontent.com/26659428/87183399-13c80980-c2b4-11ea-9f5c-29581cf7340e.png)

**Comment by motasemelgamel** [comment]
![image](https://user-images.githubusercontent.com/66404152/89838251-c223d080-db38-11ea-875c-14aae020740a.png)
![image](https://user-images.githubusercontent.com/66404152/89838273-d1a31980-db38-11ea-8fad-a475b8a3b9fa.png)

I added an event that will handle hide/show of the trees

**Comment by ciozi137** [comment]
@mo3tasem98 great. Does this change the window size?

**Comment by motasemelgamel** [comment]
No, but I think I can make it do that.

**Comment by motasemelgamel** [comment]
I think it resizes the vi window now

**Comment by ciozi137** [comment]
I think better way to approach this would be with splitter bars?
