### ISSUE TITLE
Create/Use class with abstract methods

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/DSC#23]
Need a class (or interface!) with abstract methods like "Get Historical Trace"
- Over method(s) when reading from Citadel database (like we are doing now) or postgreSQL database (like @johnbrickmaier is developing)

**Comment by ciozi137** [comment]
Maybe choose method based on choice of database?
Class architecture might be too complicated for this application. Need to think about this...

**Comment by motasemelgamel** [comment]
can you elaborate more on what you mean by "a class with abstract methods"? I don't think I understand.

**Comment by ciozi137** [comment]
Basically a parent class that defines the methods but not how they are implemented.

One example is that "get historical trace" could be defined in a "database.lvclass". Then we can have two children _inherit_ from database.lvclass:
- database.dsc.lvclass
- database.sql.lvclass.

They would each _override_ "get historical trace" with their own way to query the database. In this way you can _dynamically_, at runtime, choose or switch which specific implementation gets called.
