### ISSUE TITLE
Database Viewer: Change database without quitting application

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/DSC#24]
Give the user a way to reload a database

**Comment by motasemelgamel** [comment]
![image](https://user-images.githubusercontent.com/66404152/89842425-94905480-db43-11ea-825a-22b472029f03.png)
![image](https://user-images.githubusercontent.com/66404152/89842449-a7a32480-db43-11ea-9cae-77172700af4a.png)
I added a front panel button that will make the user able to choose which database he want to work with in real-time. If they chooses DSC while they are not connected to it, they will get an error message that the vi can't find DSC. If the connection to either database was done correctly a message "connected!" will be displayed. I edited Macro: Initialize, Data: Get Database states and added a UI: Connected state.

**Comment by motasemelgamel** [comment]
Also, I don't get the difference between TEMPerHUM, Default databases and postgres, DSC databases. I am guessing TEMPerHUM, Default exist as part of DSC and store different parameters and all of this is saved on houses of the holy. Do I understand correctly?

**Comment by ciozi137** [comment]
- default = "DSC". Citadel database with most of our historical time trace instrument data logs. Hosted on housesoftheholy _Eventually we will move all of the data to postgres_
- TEMPerHUM = another Citadel database hosted on housesoftheholy _Eventually we will move all of the data to postgres_
- postgres = new database hosted on AWS. The future.
