### ISSUE TITLE
Table Name

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/DSC#42]
How to go from Table Name and Column to Path?

e.g.:
llab_024:d000(MNK_18T--1820_IPS_Magnet_Field(T))

How can we go from MNK_18T,1820_IPS_Magnet_Field(T) to llab_024:d000?

**Comment by johnbrickmaier** [comment]
If you want to get the path for just one, I think there is a VI called
pathfinder.vi where you can find the table and the column in the database
and it will give the path.  If you run insert without valid paths, it
should bring up the VI that you saw and help configure the paths.  I’m glad
it worked!!

Jack
