### ISSUE TITLE
States and Categories

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/DSC#6]
- "Work" category is not very descriptive. I recommend making a category for "database" operations, and maybe another category for "graph" operations?
- You should reuse the existing categories, including Data, UI, Macro
- Further subdivide existing states into common states that can be reused. (you'll notice that the states "Work: Live Plot Graph, Start/End Graph, Span Graph, Seek Back Graph, Forward Graph" all contain the same code. Better to make one state called, e.g. "UI: Update Graph Value"
- I think you should also have a state called something like "UI: Update Graph Scales" for changing scale labels etc.

![image](https://user-images.githubusercontent.com/26659428/86618976-c849ee80-bf87-11ea-9f0b-6fe819775e83.png)

![image](https://user-images.githubusercontent.com/26659428/86618652-48238900-bf87-11ea-9751-bc35923a66a0.png)

![image](https://user-images.githubusercontent.com/26659428/86618781-7e610880-bf87-11ea-82d3-90e97dee1aa5.png)

**Comment by motasemelgamel** [comment]
Is there any reason we should use explicit graph reference instead of implicit graph reference if they point to the same graph?
![Explicit reference](https://user-images.githubusercontent.com/66404152/86734626-20bcd280-c000-11ea-8858-01c37159045d.JPG)
![Implicit reference](https://user-images.githubusercontent.com/66404152/86734628-20bcd280-c000-11ea-8425-8d93b46d3d69.JPG)

**Comment by motasemelgamel** [comment]
In the original code, sometimes explicit reference is used and other times implicit is used. In writing the code of the common "UI: Update Graph" state I will use only implicit reference, would that make any difference?
![Implicit reference](https://user-images.githubusercontent.com/66404152/86735159-9759d000-c000-11ea-9017-8adeebcfe175.JPG)

**Comment by ciozi137** [comment]
The difference is the explicit reference is more flexible.

You could imagine a scenario where you have multiple graphs and store the references in an array. Then you can update any one of the graphs with a state call like “UI: Update Graph >> x”, where x is the index of the graph reference.

For the database.vi application it’s not clear to me which is better, since there is only one or two graphs.

You may want to look into using the graph_utilities and xy_utilities package at some point. They are basically just wrappers for these graph property nodes, but they might be useful for doing some functions like decimating. And might be useful for the xy-graph tab. Right now it is labeled “shitty” I think because there is no effort to resample either of the arrays to make them equal.
