### ISSUE TITLE
Is this hidden control needed?

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/DSC#7]
![image](https://user-images.githubusercontent.com/26659428/86845645-cfe8c080-c077-11ea-92af-82b38aa2412c.png)

**Comment by motasemelgamel** [comment]
I am not sure. I left it as it was in the original code.

**Comment by ciozi137** [comment]
I know. You can try to figure out why it’s there and if we still need it.

**Comment by motasemelgamel** [comment]
I don't think we need it. I was looking into what it is used for and I think It only tracks the variables being plotted in the live plot and keeps them in an array of strings.

**Comment by motasemelgamel** [comment]
I noticed it is repeated in other states too, but still hidden. I think we should just remove it.

**Comment by ciozi137** [comment]
ok sounds good
