### ISSUE TITLE
What is "variables" vs "variables full string"?

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/DSC#8]
![image](https://user-images.githubusercontent.com/26659428/86845747-f1e24300-c077-11ea-96b7-9ed1187195c9.png)

**Comment by motasemelgamel** [comment]
The code outputs variables as a shared variable list and converts it to an array of strings. This is variables full string. It then loops on the string and further divides this string into variables. I am not sure how this part of the code works. The two variables are used in different places inside the VI.

Also, the code inside the Data: Get variables state is a for loop code and it doesn't have a value for its iterations. The original code was like this so I left it but I am not sure how it works if the loop doesn't stop.

![image](https://user-images.githubusercontent.com/66404152/86857817-5360dc80-c08d-11ea-84f7-dea85e5f80ce.png)

**Comment by ciozi137** [comment]
Can you elaborate “doesn't have a value for its iterations”?

**Comment by motasemelgamel** [comment]
For loops in lab view should have a value assigned to N. The loops will iterate from i = 0 to N-1. In the code here N is left empty.

**Comment by ciozi137** [comment]
A For loop will execute according to the number of elements in an array that is being indexed with an indexing terminal:
![image](https://user-images.githubusercontent.com/26659428/86941711-3de1c600-c112-11ea-8437-1ff341f55124.png)

Disabling indexing will require "N" to be wired:
![image](https://user-images.githubusercontent.com/26659428/86941805-5f42b200-c112-11ea-8fd2-3d4a677f7760.png)

**Comment by motasemelgamel** [comment]
That makes a lot of sense. I think we don't need this appending function.
![image](https://user-images.githubusercontent.com/66404152/86957340-958b2c00-c128-11ea-88da-cd4ab524ea16.png)

**Comment by ciozi137** [comment]
agree
